#!/bin/bash

fatal() {
    echo "ERROR: $1"
    exit 1
}

[ -f /etc/openapp-tuning/config ] && . /etc/openapp-tuning/config

apache_maxclients() {
	MEMUSAGE=$1

	MEM=$(grep MemTotal: /proc/meminfo | awk ' { print $2 } ')
	MAXCLIENTS=$(($MEM/100*$MEMPERC/25000))

	echo $MAXCLIENTS
}

apache_config() {
	OPENAPP_APP=$1

	CONFFILE=${CONFDIR}/openapp-tuning-apache.conf

	[ "$TUNE_APACHE" = "true" ] || return

	# Define variables
	case "${OPENAPP_APP}" in
		joomla|wordpress) 
			KEEPALIVE=0
			STARTSRV=2
			MINSPARESRV=1
			MAXSPARESRV=3
			MAXRQPCHILD=1000
			MEMPERC=80
		;;

	esac

	# The number of MaxClients is $MEMPERC % of the total memory, divided by 25000
	# (the avg size of an apache process)
	MAXCLIENTS=$(apache_maxclients $MEMPERC)

	cat <<EOF > ${CONFFILE}

# Beware! This file will be overwritten on reboots. If you want to tune Apache
# by yourself, disable apache in /etc/openapp-tuning/config

KeepAliveTimeout ${KEEPALIVE}

<IfModule mpm_prefork_module>
	StartServers          ${STARTSRV}
	MinSpareServers       ${MINSPARESRV}
	MaxSpareServers       ${MAXSPARESRV}
	MaxClients            ${MAXCLIENTS}
	MaxRequestsPerChild   ${MAXRQPCHILD}
</IfModule>
EOF
}

mysql_config() {
	OPENAPP_APP=$1

	CONFFILE=${CONFDIR}/openapp-tuning-mysql.conf

	[ "$TUNE_MYSQL" = "true" ] || return

	MEM=$(grep MemTotal: /proc/meminfo | awk ' { print $2 } ')

	# Define variables
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			APACHEMEMPERC=80
			QCACHE_LIM=4m
			QCACHE_SIZE=32m
			JOINB_SIZE=1m
			KEYBUFFER=4m
			SKIP_INNODB=1
			MAX_CONN=$(($(apache_maxclients $APACHEMEMPERC)+5))
			TABLE_CACHE=50
		;;
		mysql)
			QCACHE_LIM=4m
			QCACHE_SIZE=128m
			JOINB_SIZE=4m
			SKIP_INNODB=0
			MAX_CONN=$(($MEM/10240))        # One per 10M of memory
			TABLE_CACHE=1024
			INNO_BPS=$(($MEM/100*60/1024))m # 60% of total memory
			INNO_AMPS=16m
			INNO_LFS=256m
			INNO_LBS=8m
			INNO_LWT=120
			INNO_TC=$(($(grep -c ^processor /proc/cpuinfo)*2))
			INNO_FLATC=1
			INNO_FM=O_DIRECT
			BINLOG_CS=2m
			TABLE_O_CACHE=$TABLE_CACHE
			KEY_BS=$(($MEM/100*10/1024))m   # 10% of toal memory
		;;
	esac

	cat <<EOF > ${CONFFILE}

# Beware! This file will be overwritten on reboots. If you want to tune Mysql
# by yourself, disable apache in /etc/openapp-tuning/config

[mysqld]
query_cache_limit       = $QCACHE_LIM
query_cache_size        = $QCACHE_SIZE
join_buffer_size        = $JOINB_SIZE
skip-innodb             = $SKIP_INNODB
max-connections         = $MAX_CONN
table_cache             = $TABLE_CACHE
EOF

	if [ ${SKIP_INNODB} -eq 0 ]; then
		cat <<EOF >> ${CONFFILE}
innodb_buffer_pool_size   = $INNO_BPS
innodb_additional_mem_pool_size = $INNO_AMPS
innodb_log_file_size      = $INNO_LFS
innodb_log_buffer_size    = $INNO_LBS
innodb_lock_wait_timeout  = $INNO_LWT
innodb_thread_concurrency = $INNO_TC
innodb_flush_log_at_trx_commit  = $INNO_FLATC
innodb_flush_method       = $INNO_FM
binlog_cache_size         = $BINLOG_CS
table_open_cache          = $TABLE_O_CACHE
key_buffer_size           = $KEY_BS

EOF
	fi
}

enable_config() {
	OPENAPP_APP=$1

	MYSQL_CONFFILE=${CONFDIR}/openapp-tuning-mysql.conf
	APACHE_CONFFILE=${CONFDIR}/openapp-tuning-apache.conf
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			[ "$TUNE_APACHE" = "true" ] && echo "ln -s ${APACHE_CONFFILE} /etc/apache2/conf.d/openapp-tuning.conf"
			[ "$TUNE_MYSQL" = "true" ]  && echo "ln -s ${MYSQL_CONFFILE} /etc/mysql/conf.d/openapp-tuning.cnf"
		;;
		mysql)
			[ "$TUNE_MYSQL" = "true" ]  && echo "ln -s ${MYSQL_CONFFILE} /etc/mysql/conf.d/openapp-tuning.cnf"
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
}

disable_config() {
	OPENAPP_APP=$1

	case "${OPENAPP_APP}" in
		joomla|wordpress)
			echo "rm /etc/apache2/conf.d/openapp-tuning.conf"
		;;
		mysql)
			echo "rm /etc/mysql/conf.d/openapp-tuning.cnf"
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
}

[ -z $1 ] || OPENAPP_APP=$1
[ -z $2 ] || ACTION=$2
[ -z ${ACTION} ] && fatal "Not enough parameters! (Need 'openapp-app' 'start|stop'"

if [ "${ACTION}" = "start" ]; then
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			apache_config ${OPENAPP_APP}
			mysql_config ${OPENAPP_APP}
		;;
		mysql)
			mysql_config ${OPENAPP_APP}
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
fi

case "${ACTION}" in
	start)
		enable_config ${OPENAPP_APP}
	;;
	stop)
		disable_config ${OPENAPP_APP}
	;;
esac

