#!/bin/bash

fatal() {
    echo "ERROR: $1"
    exit 1
}

[ -f /etc/openapp-tuning/config ] || fatal "No configuration found. Is OpenApp really installed?"

. /etc/openapp-tuning/config

[ -z ${CONFDIR} ] && fatal "CONFDIR Not defined, not tuning anything"

[ -z $1 ] || OPENAPP_APP=$1
[ -z $2 ] || ACTION=$2
[ -z $3 ] || [ "$3" = "dorestart" ] && DORESTART=yes
[ -z ${ACTION} ] && fatal "Not enough parameters! (Need 'openapp-app' 'start|stop'"

apache_maxclients() {
	MEMUSAGE=$1

	MEM=$(grep MemTotal: /proc/meminfo | awk ' { print $2 } ')
	MAXCLIENTS=$(($MEM/100*$MEMPERC/25000))

	echo $MAXCLIENTS
}

apache_config() {
	OPENAPP_APP=$1

	CONFFILE=${CONFDIR}/openapp-tuning-apache.conf.tmp

	[ "$TUNE_APACHE" = "true" ] || return

	# Define variables
	case "${OPENAPP_APP}" in
		joomla|wordpress) 
			KEEPALIVE=0
			STARTSRV=2
			MINSPARESRV=1
			MAXSPARESRV=3
			MAXRQPCHILD=1000
			MEMPERC=80
		;;

	esac

	# The number of MaxClients is $MEMPERC % of the total memory, divided by 25000
	# (the avg size of an apache process)
	MAXCLIENTS=$(apache_maxclients $MEMPERC)

	cat <<EOF > ${CONFFILE}

# Beware! This file will be overwritten on reboots. If you want to tune Apache
# by yourself, disable apache in /etc/openapp-tuning/config

KeepAliveTimeout ${KEEPALIVE}

<IfModule mpm_prefork_module>
	StartServers          ${STARTSRV}
	MinSpareServers       ${MINSPARESRV}
	MaxSpareServers       ${MAXSPARESRV}
	MaxClients            ${MAXCLIENTS}
	MaxRequestsPerChild   ${MAXRQPCHILD}
</IfModule>
EOF
}

mysql_config() {
	OPENAPP_APP=$1

	CONFFILE=${CONFDIR}/openapp-tuning-mysql.conf.tmp

	[ "$TUNE_MYSQL" = "true" ] || return

	MEM=$(grep MemTotal: /proc/meminfo | awk ' { print $2 } ')

	# Define variables
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			APACHEMEMPERC=80
			QCACHE_LIM=4m
			QCACHE_SIZE=32m
			JOINB_SIZE=1m
			KEYBUFFER=4m
			SKIP_INNODB=1
			MAX_CONN=$(($(apache_maxclients $APACHEMEMPERC)+5))
			TABLE_CACHE=50
		;;
		mysql)
			QCACHE_LIM=4m
			QCACHE_SIZE=128m
			JOINB_SIZE=4m
			SKIP_INNODB=0
			MAX_CONN=$(($MEM/10240))        # One per 10M of memory
			TABLE_CACHE=1024
			INNO_BPS=$(($MEM/100*60/1024))m # 60% of total memory
			INNO_AMPS=16m
			INNO_LFS=256m
			INNO_LBS=8m
			INNO_LWT=120
			INNO_TC=$(($(grep -c ^processor /proc/cpuinfo)*2))
			INNO_FLATC=1
			INNO_FM=O_DIRECT
			BINLOG_CS=2m
			TABLE_O_CACHE=$TABLE_CACHE
			KEY_BS=$(($MEM/100*10/1024))m   # 10% of toal memory
		;;
	esac

	cat <<EOF > ${CONFFILE}

# Beware! This file will be overwritten on reboots. If you want to tune Mysql
# by yourself, disable apache in /etc/openapp-tuning/config

[mysqld]
query_cache_limit       = $QCACHE_LIM
query_cache_size        = $QCACHE_SIZE
join_buffer_size        = $JOINB_SIZE
skip-innodb             = $SKIP_INNODB
max-connections         = $MAX_CONN
table_cache             = $TABLE_CACHE
EOF

	if [ ${SKIP_INNODB} -eq 0 ]; then
		cat <<EOF >> ${CONFFILE}
innodb_buffer_pool_size   = $INNO_BPS
innodb_additional_mem_pool_size = $INNO_AMPS
innodb_log_file_size      = $INNO_LFS
innodb_log_buffer_size    = $INNO_LBS
innodb_lock_wait_timeout  = $INNO_LWT
innodb_thread_concurrency = $INNO_TC
innodb_flush_log_at_trx_commit  = $INNO_FLATC
innodb_flush_method       = $INNO_FM
binlog_cache_size         = $BINLOG_CS
table_open_cache          = $TABLE_O_CACHE
key_buffer_size           = $KEY_BS
innodb_file_per_table     = 1
EOF
	fi
}

detect_mysql_iblogfile_size() {
	MYSQL_CONFFILE=${CONFDIR}/openapp-tuning-mysql.conf

	FILESIZE=$(stat -t /var/lib/mysql/ib_logfile1 | cut -f 2 -d ' ')
	CONFIGSIZE=$(grep innodb_log_file_size ${MYSQL_CONFFILE} | cut -f2 -d '=')

	SIZEMULTIP=$(echo ${CONFIGSIZE: -1})

	BYTES=$(echo ${CONFIGSIZE%%${SIZEMULTIP}})

	case "$SIZEMULTIP" in
		m)
			BYTES=$(($BYTES*1024*1024))
		;;
		g)
			BYTES=$(($BYTES*1024*1024*1024))
		;;
	esac

	[ $BYTES -ne $FILESIZE ] && echo "change"
}

enable_config() {
	OPENAPP_APP=$1

	MYSQL_CONFFILE=${CONFDIR}/openapp-tuning-mysql.conf
	APACHE_CONFFILE=${CONFDIR}/openapp-tuning-apache.conf
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			diff ${APACHE_CONFFILE}.tmp ${APACHE_CONFFILE} > /dev/null
			if [ $? -gt 0 ]; then
				mv ${APACHE_CONFFILE}.tmp ${APACHE_CONFFILE} 
				[ "$TUNE_APACHE" = "true" ] || return
				ln -sf ${APACHE_CONFFILE} /etc/apache2/conf.d/openapp-tuning.conf
				[ "$DORESTART" = "yes" ] && /etc/init.d/apache2 restart
			else
				rm ${APACHE_CONFFILE}.tmp
			fi
		;;
		mysql|joomla|wordpress)
			diff ${MYSQL_CONFFILE}.tmp ${MYSQL_CONFFILE} > /dev/null
			if [ $? -gt 0 ]; then
				mv ${MYSQL_CONFFILE}.tmp ${MYSQL_CONFFILE}
				[ "$TUNE_MYSQL" = "true" ] || return
				IBLOGCHANGE=$(detect_mysql_iblogfile_size)
				[ "$DORESTART" = "yes" ] && stop mysql
				if [ "$IBLOGCHANGE" = "change" ]; then
					mkdir /var/backups/mysql
					mv /var/lib/mysql/ib_logfile* /var/backups/mysql
				fi
				cp ${MYSQL_CONFFILE} /etc/mysql/conf.d/openapp_tuning.cnf
				[ "$DORESTART" = "yes" ] && start mysql
			else
				rm ${MYSQL_CONFFILE}.tmp
			fi
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
}

disable_config() {
	OPENAPP_APP=$1

	case "${OPENAPP_APP}" in
		joomla|wordpress)
			rm /etc/apache2/conf.d/openapp-tuning.conf
			rm /etc/mysql/conf.d/openapp-tuning.cnf
		;;
		mysql)
			rm /etc/mysql/conf.d/openapp-tuning.cnf
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
}

if [ "${ACTION}" = "start" ]; then
	case "${OPENAPP_APP}" in
		joomla|wordpress)
			apache_config ${OPENAPP_APP}
			mysql_config ${OPENAPP_APP}
		;;
		mysql)
			mysql_config ${OPENAPP_APP}
		;;
		*)
			fatal "Unknown OpenApp application"
		;;
	esac
fi

case "${ACTION}" in
	start)
		enable_config ${OPENAPP_APP}
	;;
	stop)
		disable_config ${OPENAPP_APP}
	;;
esac

